version: '3'
services:
  postgres:
    image: postgres:13.4-alpine
    container_name: postgres-inv
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    restart: always
